// data.js - FociStore App and Game Data
// Optimized: Cleaned syntax, standard indentation, and simplified date formats.

const appData = {
    apps: [
        {
            id: 1,
            name: "WhatsApp MOD",
            description: "Enhanced version with extra features like theme customization, privacy options, and more",
            category: "social",
            image: "assets/images/fmwhatsapp.png",
            size: "95 MB",
            version: "v2.23.5.76",
            rating: 4.7,
            popularity: 95,
            releaseDate: "2024-10-20",
            downloads: "10K+",
            downloadUrl: "https://getkukuymun.site/url/2A8QZ54HRrD",
            badge: "Trending"
        },
        {
            id: 2,
            name: "Instagram MOD",
            description: "Download photos, videos, stories with enhanced privacy and customization options.",
            category: "social",
            image: "assets/images/Insta-Pro-APK.png",
            size: "143 MB",
            version: "v289.0.0.18.109",
            rating: 4.7,
            popularity: 92,
            releaseDate: "2024-10-19",
            downloads: "8K+",
            downloadUrl: "https://getkukuymun.site/url/2A8QZ54HRrD",
            badge: "New"
        },
        {
            id: 3,
            name: "YouTube MOD",
            description: "Ad-free YouTube experience with background play and video download capabilities.",
            category: "media",
            image: "assets/images/app.revanced.android.youtube.200.png",
            size: "85 MB",
            version: "v18.45.43",
            rating: 4.8,
            popularity: 98,
            releaseDate: "2024-10-22",
            downloads: "15K+",
            downloadUrl: "https://vanced.to/",
            badge: "Popular"
        },
        {
            id: 4,
            name: "File Manager MOD",
            description: "Advanced file management with root access, cloud integration, and premium themes.",
            category: "tools",
            image: "assets/images/video-player-all-format-1 mobile.png",
            size: "8 MB",
            version: "v4.2.1",
            rating: 4.8,
            popularity: 80,
            releaseDate: "2024-10-18",
            downloads: "5K+",
            downloadUrl: "https://liteapks.com/download/file-manager-77834",
            badge: "Pro"
        },
        {
            id: 5,
            name: "XPlayer",
            description: "XPlayer Mod APK is an impressive video player tool and gives you the best experience.",
            category: "media",
            image: "assets/images/xplayer.png",
            size: "38 MB",
            version: "v2.4.8.2",
            rating: 4.5,
            popularity: 82,
            releaseDate: "2024-10-17",
            downloads: "7K+",
            downloadUrl: "https://liteapks.com/download/xplayer-5858",
            badge: "Enhanced"
        },
        {
            id: 6,
            name: "Office Suite MOD",
            description: "Complete office suite with PDF editing, cloud sync, and all premium features unlocked.",
            category: "productivity",
            image: "assets/images/office-suite.png",
            size: "120 MB",
            version: "v14.8.4",
            rating: 4.7,
            popularity: 85,
            releaseDate: "2024-10-16",
            downloads: "6K+",
            downloadUrl: "#",
            badge: "Premium"
        },
        {
            id: 7,
            name: "TikTok MOD",
            description: "Download videos without watermark, unlimited features and enhanced privacy options.",
            category: "social",
            image: "assets/images/tiktok-mod.png",
            size: "120 MB",
            version: "v30.5.4",
            rating: 4.6,
            popularity: 96,
            releaseDate: "2024-10-21",
            downloads: "15K+",
            downloadUrl: "https://example.com/tiktok",
            badge: "Popular"
        },
        {
            id: 8,
            name: "Spotify MOD",
            description: "Ad-free music, unlimited skips, and premium features unlocked.",
            category: "media",
            image: "assets/images/spotify-mod.png",
            size: "85 MB",
            version: "v8.8.96",
            rating: 4.9,
            popularity: 99,
            releaseDate: "2024-10-23",
            downloads: "20K+",
            downloadUrl: "https://example.com/spotify",
            badge: "Premium"
        },
        {
            id: 9,
            name: "Snapchat MOD",
            description: "Save snaps, view stories anonymously, and access premium filters.",
            category: "social",
            image: "assets/images/snapchat-mod.png",
            size: "95 MB",
            version: "v12.1.0.30",
            rating: 4.5,
            popularity: 90,
            releaseDate: "2024-10-15",
            downloads: "9K+",
            downloadUrl: "#",
            badge: "New"
        }
    ],
    games: [
        {
            id: 1,
            name: "Subway Surfers MOD",
            description: "Unlimited coins, keys, and all characters unlocked. Run endlessly without restrictions.",
            category: "action",
            image: "assets/images/subway-surfers.png",
            size: "150 MB",
            version: "v3.12.1",
            rating: 4.8,
            popularity: 98,
            releaseDate: "2024-10-23",
            downloads: "25K+",
            downloadUrl: "https://an1.com/file_4683-dw.html",
            badge: "Unlimited"
        },
        {
            id: 2,
            name: "Asphalt 9 MOD",
            description: "Unlimited credits, all cars unlocked, and premium features for the ultimate racing experience.",
            category: "racing",
            image: "assets/images/asphalt-9.png",
            size: "2.1 GB",
            version: "v3.9.4",
            rating: 4.9,
            popularity: 95,
            releaseDate: "2024-10-22",
            downloads: "12K+",
            downloadUrl: "https://asphalt-9-legends-mod.apkresult.io/download",
            badge: "Premium"
        },
        {
            id: 3,
            name: "Candy Crush MOD",
            description: "Unlimited lives, boosters, and all levels unlocked. Sweet gaming without limits.",
            category: "puzzle",
            image: "assets/images/candy-crush.png",
            size: "95 MB",
            version: "v1.260.1.2",
            rating: 4.7,
            popularity: 90,
            releaseDate: "2024-10-21",
            downloads: "18K+",
            downloadUrl: "https://candy-crush-soda-saga.apkrabi.com/download/",
            badge: "Unlimited"
        },
        {
            id: 4,
            name: "Minecraft MOD",
            description: "Unlocked skins, texture packs, and premium features for unlimited creativity.",
            category: "adventure",
            image: "assets/images/minecraft.png",
            size: "180 MB",
            version: "v1.20.15.01",
            rating: 4.9,
            popularity: 96,
            releaseDate: "2024-10-20",
            downloads: "15K+",
            downloadUrl: "#",
            badge: "Premium"
        },
        {
            id: 5,
            name: "FIFA Mobile MOD",
            description: "Unlimited coins, all players unlocked, and premium features for the ultimate football experience.",
            category: "sports",
            image: "assets/images/fifa-mobile.png",
            size: "1.2 GB",
            version: "v17.0.14",
            rating: 4.8,
            popularity: 88,
            releaseDate: "2024-10-19",
            downloads: "10K+",
            downloadUrl: "#",
            badge: "Enhanced"
        },
        {
            id: 6,
            name: "Call of Duty MOD",
            description: "Unlimited CP, all weapons unlocked, and premium battle pass for ultimate warfare.",
            category: "action",
            image: "assets/images/call-of-duty.png",
            size: "2.5 GB",
            version: "v1.0.39",
            rating: 4.9,
            popularity: 97,
            releaseDate: "2024-10-18",
            downloads: "20K+",
            downloadUrl: "#",
            badge: "Pro"
        },
        {
            id: 7,
            name: "Temple Run 2 MOD",
            description: "Unlimited coins, all characters unlocked, and infinite energy for endless running.",
            category: "adventure",
            image: "assets/images/temple-run.png",
            size: "80 MB",
            version: "v1.100.0",
            rating: 4.6,
            popularity: 85,
            releaseDate: "2024-10-17",
            downloads: "8K+",
            downloadUrl: "#",
            badge: "Unlimited"
        },
        {
            id: 8,
            name: "PUBG Mobile MOD",
            description: "Unlimited UC, aim assist, and all skins unlocked for battle royale dominance.",
            category: "action",
            image: "assets/images/pubg-mobile.png",
            size: "1.8 GB",
            version: "v3.0.0",
            rating: 4.9,
            popularity: 100,
            releaseDate: "2024-10-24",
            downloads: "30K+",
            downloadUrl: "#",
            badge: "Pro"
        },
        {
            id: 9,
            name: "Clash of Clans MOD",
            description: "Unlimited gems, gold, and elixir with all troops and buildings unlocked for epic battles.",
            category: "strategy",
            image: "assets/images/clash-of-clans.png",
            size: "150 MB",
            version: "v14.0.10",
            rating: 4.8,
            popularity: 93,
            releaseDate: "2024-10-25",
            downloads: "22K+",
            downloadUrl: "#",
            badge: "Enhanced"
        }
    ]
};